version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8000:8000
    depends_on:
    - mysqldb

  mysqldb:
    image: mysql
    environment:
    - MYSQL_DATABASE=stats_database
    - MYSQL_ROOT_PASSWORD=password
